server {
    listen 80;
    include /etc/nginx/mime.types;
    root /usr/share/nginx/html;
    index index.html index.htm;
    server_tokens off;

    location @index {
        add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
    }

    location ~* ^.+\.(css|js|png|jpg|jpeg|gif|ico)$ {
        expires 1m;
        add_header Cache-Control "public, immutable";
        try_files $uri $uri/ /index.html;
    }

    location / {
        expires 1m;
        add_header Cache-Control "public, immutable";
        try_files $uri $uri/ /index.html;
    }
}
