server {
    listen 80;
    include /etc/nginx/mime.types;
    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        add_header Cache-Control no-store;
    }

    location ~* \.(png|jpg|jpeg|gif|ico)$ {
        expires 7d;
        etag on;
    }
}
