#! venv/bin/python3.10

from pygit2 import Repository
from cmd import Cmd
import os
from aeosa import appscript
from termcolor import colored
import toml
 
with open('devUtilsConfig.toml', 'r') as f:
    config = toml.load(f)
 
class DevUtilsCmd(Cmd):
    #{os.environ['USER']}-
    prompt = colored(f"{Repository('.').head.shorthand} > ", "light_green")
    intro = colored("Welcome to devUtil tool " + os.environ['USER'], "cyan")

    def do_localDevelopMode(self, inp):
        currDir = os.getcwd()
        appscript.app('Terminal').do_script('cd ' + currDir + f'; docker compose up --build')
        # os.system('docker compose up --build -d')

    def do_resumeLocalDevelopMode(self, inp):
        currDir = os.getcwd()
        appscript.app('Terminal').do_script('cd ' + currDir + f'; docker compose up')

    def do_stopLocalDevelopMode(self, inp):
        os.system('docker compose stop')
    
    def do_downLocalDevelopMode(self, inp):
        os.system('docker compose down')

    def do_executeTests(self, inp):
        os.system('cd backend/apigateway; ./gradlew test')
        os.system('cd backend/services/userservice; ./gradlew test')
        os.system('cd backend/services/courseservice; ./gradlew test')
        os.system('cd backend/services/exerciseservice; ./gradlew test')
        os.system('cd backend/services/storageservice; ./gradlew test')
        os.system('cd backend/services/executorservice; ./gradlew test')

    def do_exit(self, inp):
        return True
    
    def do_start(self, inp: str):
        if inp == '':
            return
        for s in inp.split(' '):
            os.system(f'docker compose start {s}')
    
    def do_restart(self, inp: str):
        if inp == '':
            return
        for s in inp.split(' '):
            os.system(f'docker compose build {s} && docker compose create {s} && docker compose restart {s}')

    def do_stop(self, inp: str):
        if inp == '':
            return
        for s in inp.split(' '):
            os.system(f'docker compose stop {s}')

    def do_list_services(self, inp):
        os.system(f'docker compose config --services')

    def do_deployToProd(self, inp):
        os.system(f"DOCKER_HOST={config['production']['docker_engine']} docker compose -f docker-compose-prod.yml --project-name avogador --env-file production.env up -d --build")

    def do_sandboxBuildPush(self, inp):
        os.system('docker buildx build --push --platform linux/amd64  --tag gotti27/runtime-env:stable ./sandboxImage')

    #### ----- ####

    def help_localDevelopMode(self):
        print('build and start the local backend cluster instance')

    def help_resumeLocalDevelopMode(self):
        print('start the local cluster instance without forcing build')
    
    def help_list_services(self):
        print('get a list of the services')

    def help_restart(self):
        print('rebuild, recreate and restart the listed services')

    def help_exit(self):
        print("exit the app")

    def help_stopLocalDevelopMode(self):
        print('stop the local backend cluster instance')

    def help_downLocalDevelopMode(self):
        print('remove the local backend cluster instance')

    def help_executeTests(self):
        print('execute all junit backend tests')

    def help_start(self):
        print('start the listed services')

    def help_stop(self):
        print('stop the listed services')

    def help_deployToProd(self):
        print('deploys all the microservices to production')

    def help_sandboxBuildPush(self):
        print('build and push the sandbox docker image')

p = DevUtilsCmd()
p.cmdloop()
