version: "3.8"

services:
  hello-world:
    image: "hello-world"
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "5m"
  
  webapp:
    image: avogador-webapp:${BRANCH:-latest}
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${REACT_TARGET}
    network: host
    args:
      OBFUSCATE_DIRECTIVE: ${OBFUSCATE_DIRECTIVE}
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "5m"
    ports:
      - "${REACT_PORT}:3000"

