version: "3.8"

services:
  apigateway:
    image: "avogador-apigateway:dev-${BRANCH:-latest}" 
    restart: always
    build:
      context: ./backend/apigateway
      network: host
      dockerfile: Dockerfile.dev
      target: ${APIGATEWAY_TARGET}
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "5m"
    environment:
      sentry.dsn: ${BACKEND_GLITCHTIP_DSN}
      # spring.rabbitmq.host: ${RABBITMQ_BROKER_HOST}
      # spring.rabbitmq.username: ${RABBITMQ_USERNAME}
      # spring.rabbitmq.password: ${RABBITMQ_PASSWORD}
      server.port: 80
      # logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: ${SPRING_LOGGING_LEVEL}
      logging.level.org.springframework.cloud.gateway: ${SPRING_LOGGING_LEVEL}
      spring.output.ansi.enabled: ${SPRING_OUTPUT_ANSI_ENABLED}
      # jwt.secret: ${JWT_SECRET}
      # rabbit.hostname: ${RABBITMQ_BROKER_HOST}
      # spring.servlet.multipart.max-file-size: 2GB
      # spring.servlet.multipart.max-request-size: 2GB
      spring.profiles.active: ${APIGATEWAY_PROFILE}
      spring.lifecycle.timeout-per-shutdown-phase: 1m
      server.shutdown: graceful
      security.allowed.origins: ${APIGATEWAY_ALLOWED_ORIGINS}
      # multipart.enabled: false
    ports:
      - "${APIGATEWAY_PORT}:80"
    networks:
      - avogador-inner-network

  users:
    image: "avogador-userservice:dev-${BRANCH:-latest}" 
    restart: always
    build:
      context: ./backend/services/userservice
      network: host
      dockerfile: Dockerfile.dev
      target: ${USERSERVICE_TARGET}
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "5m"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      sentry.dsn: ${BACKEND_GLITCHTIP_DSN}
      # spring.rabbitmq.host: ${RABBITMQ_BROKER_HOST}
      # spring.rabbitmq.username: ${RABBITMQ_USERNAME}
      # spring.rabbitmq.password: ${RABBITMQ_PASSWORD}
      server.port: 80
      spring.datasource.url: ${USERSERVICE_DATASOURCE_URL}
      spring.datasource.username: ${USERSERVICE_DATASOURCE_USERNAME}
      spring.datasource.password: ${USERSERVICE_DATASOURCE_PASSWORD}
      spring.jpa.hibernate.ddl-auto: ${USERSERVICE_JPA_HIBERNATE_DDL_AUTO}
      spring.jpa.properties.hibernate.dialect: ${USERSERVICE_JPA_PROPERTIES_HIBERNATE_DIALECT}
      logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: ${SPRING_LOGGING_LEVEL}
      spring.output.ansi.enabled: ${SPRING_OUTPUT_ANSI_ENABLED}
      jwt.secret: ${JWT_SECRET}
      # rabbit.hostname: ${RABBITMQ_BROKER_HOST}
      # spring.servlet.multipart.max-file-size: 2GB
      # spring.servlet.multipart.max-request-size: 2GB
      spring.profiles.active: ${USERSERVICE_PROFILE}
      spring.lifecycle.timeout-per-shutdown-phase: 1m
      server.shutdown: graceful
      security.allowed.origins: ${USERSERVICE_ALLOWED_ORIGINS}
      # multipart.enabled: false
      spring.mail.host: ${MAIL_HOST}
      spring.mail.username: ${MAIL_USER} 
      spring.mail.password: ${MAIL_PASSWORD} 
      spring.mail.properties.mail.transport.protocol: smtp
      spring.mail.properties.mail.smtp.port: 25
      spring.mail.properties.mail.smtp.auth: true
      spring.mail.properties.mail.smtp.starttls.enable: true
      spring.mail.properties.mail.smtp.starttls.required: true
      spring.mail.properties.mail.debug: false
    ports:
      - "${USERSERVICE_PORT}:80"
    networks:
      - avogador-inner-network

  courses:
    image: "avogador-courseservice:dev-${BRANCH:-latest}" 
    restart: always
    build:
      context: ./backend/services/courseservice
      network: host
      dockerfile: Dockerfile.dev
      target: ${COURSESERVICE_TARGET}
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "5m"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      spring.rabbitmq.host: ${RABBITMQ_BROKER_HOST}
      spring.rabbitmq.username: ${COURSES_RABBITMQ_USERNAME}
      spring.rabbitmq.password: ${COURSES_RABBITMQ_PASSWORD}
      server.port: 80
      spring.datasource.url: ${COURSESERVICE_DATASOURCE_URL}
      spring.datasource.username: ${COURSESERVICE_DATASOURCE_USERNAME}
      spring.datasource.password: ${COURSESERVICE_DATASOURCE_PASSWORD}
      spring.jpa.hibernate.ddl-auto: ${COURSESERVICE_JPA_HIBERNATE_DDL_AUTO}
      spring.jpa.properties.hibernate.dialect: ${COURSESERVICE_JPA_PROPERTIES_HIBERNATE_DIALECT}
      logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: ${SPRING_LOGGING_LEVEL}
      spring.output.ansi.enabled: ${SPRING_OUTPUT_ANSI_ENABLED}
      joinCode.secret: ${JOINCODE_SECRET}
      # jwt.secret: ${JWT_SECRET}
      # rabbit.hostname: ${RABBITMQ_BROKER_HOST}
      # spring.servlet.multipart.max-file-size: 2GB
      # spring.servlet.multipart.max-request-size: 2GB
      spring.profiles.active: ${COURSESERVICE_PROFILE}
      spring.lifecycle.timeout-per-shutdown-phase: 1m
      server.shutdown: graceful
      security.allowed.origins: ${COURSESERVICE_ALLOWED_ORIGINS}
      # multipart.enabled: false
    ports:
      - "${COURSESERVICE_PORT}:80"
    networks:
      - avogador-inner-network

  filesystem:
    image: "avogador-filesystemservice:dev-${BRANCH:-latest}" 
    restart: always
    build:
      context: ./backend/services/filesystemservice
      network: host
      dockerfile: Dockerfile.dev
      target: ${FILESYSTEMSERVICE_TARGET}
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "5m"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      spring.rabbitmq.host: ${RABBITMQ_BROKER_HOST}
      spring.rabbitmq.username: ${FILESYSTEMSERVICE_RABBITMQ_USERNAME}
      spring.rabbitmq.password: ${FILESYSTEMSERVICE_RABBITMQ_PASSWORD}
      server.port: 80
      logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: ${SPRING_LOGGING_LEVEL}
      spring.output.ansi.enabled: ${SPRING_OUTPUT_ANSI_ENABLED}
      # rabbit.hostname: ${RABBITMQ_BROKER_HOST}
      # spring.servlet.multipart.max-file-size: 2GB
      # spring.servlet.multipart.max-request-size: 2GB
      spring.profiles.active: ${FILESYSTEMSERVICE_PROFILE}
      spring.lifecycle.timeout-per-shutdown-phase: 1m
      server.shutdown: graceful
      # multipart.enabled: false
    ports:
      - "${FILESYSTEMSERVICE_PORT}:80"
    volumes:
      - filesystem-volume:/avogador
    networks:
      - avogador-inner-network

  rabbitmq:
    hostname: avogador-rabbitmq
    image: rabbitmq:3-management
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "5m"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 15s
      retries: 3
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    networks:
      - avogador-inner-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
    ports:
      # - "5672:5672"
      - "15672:15672"

volumes:
  rabbitmq-data:
  
  filesystem-volume:
    driver: local
    driver_opts:
      type: cifs    
      device: //${FILESYSTEMSERVICE_VOLUME_ADDRESS}/${FILESYSTEMSERVICE_VOLUME_NAME}
      o: "addr=${FILESYSTEMSERVICE_VOLUME_ADDRESS},username=${FILESYSTEMSERVICE_VOLUME_USER},password=${FILESYSTEMSERVICE_VOLUME_PASS},file_mode=0777,dir_mode=0777"

networks:
  avogador-inner-network: