version: "3.8"

services:
  usercourse:
    image: "avogador-usercourse:dev-${BRANCH:-latest}" 
    restart: always
    build:
      context: ./backend/services/usercourse/
      network: host
      dockerfile: Dockerfile
      target: run
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "5m"
    #environment:
    #  server.port: 8080
    ports:
      - "${PROJECTS_PORT}:8080"
    networks:
      - avogador-inner-network

networks:
  avogador-inner-network: