name: Jenkins
run-name: Jenkins Triggered by ${{ github.actor }}
on: [push]
jobs:
  Trigger-Jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: install MostSerene Root certificate
        run: |
          whoami 
          sudo mkdir /usr/local/share/ca-certificates/mostSerene
          sudo ls -l /usr/local/share/ca-certificates/
          sudo touch /usr/local/share/ca-certificates/mostSerene/mostSereneCA.pem
          sudo chmod 777 /usr/local/share/ca-certificates/mostSerene/mostSereneCA.pem
          sudo ls -l /usr/local/share/ca-certificates/mostSerene/
          sudo echo "${{ secrets.CERT }}" > /usr/local/share/ca-certificates/mostSerene/mostSereneCA.pem
          sudo update-ca-certificates

      - name: Set up WireGuard
        uses: egor-tensin/setup-wireguard@v1
        with:
          endpoint: '${{ secrets.ENDPOINT }}'
          endpoint_public_key: '${{ secrets.ENDPOINT_PUBLIC }}'
          ips: '${{ secrets.IPS }}'
          allowed_ips: '${{ secrets.ALLOWED_IPS }}'
          private_key: '${{ secrets.PRIVATE }}'
          # preshared_key: '${{ secrets.PRESHARED }}'
        
      - name: testing vpn link
        run: |
          sudo ls -l /usr/local/share/ca-certificates/mostSerene/
          ping -c 1 dev-server.sanve.mostserene.eu
    
      - name: Trigger jenkins job
        run: |
          curl -X POST --insecure -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" https://dev-server.sanve.mostserene.eu:8000/job/avogador/build?token=github-action
