name: Jenkins
run-name: ${{ github.actor }}
on: [push]
jobs:
  Trigger-Jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: install MostSerene Root certificate
        run: |
          whoami 
          sudo mkdir /usr/local/share/ca-certificates/mostSerene
          sudo ls /usr/local/share/ca-certificates/
          sudo echo "${{ secrets.CERT }}" > /usr/local/share/ca-certificates/mostSerene/mostSereneCA.pem
          sudo update-ca-certificates

      - name: Set up WireGuard
        uses: egor-tensin/setup-wireguard@v1
        with:
          endpoint: '${{ secrets.ENDPOINT }}'
          endpoint_public_key: '${{ secrets.ENDPOINT_PUBLIC }}'
          ips: '${{ secrets.IPS }}'
          allowed_ips: '${{ secrets.ALLOWED_IPS }}'
          private_key: '${{ secrets.PRIVATE }}'
          # preshared_key: '${{ secrets.PRESHARED }}'
    
      - name: Trigger jenkins job
        uses: joshlk/jenkins-githubaction@master
        with:
          url: https://dev-server.sanve.mostserene.eu
          job_name: jenkins_job_name
          username: ${{ secrets.JENKINS_USER }}
          api_token: ${{ secrets.JENKINS_TOKEN }}
          timeout: "1000"
