name: PR CICD pipeline
run-name: PR pipeline for ${{ github.ref }}
on:
  workflow_dispatch:
  pull_request:
jobs:
  Users:
    uses: ./.github/workflows/pr/microservice-pr-cicd.yml
    with:
      microservice: userservice
    secrets: inherit
