package eu.mostserene.avogador.userservice.users;

import com.google.common.hash.Hashing;
import eu.mostserene.avogador.userservice.mail.EmailService;
import eu.mostserene.avogador.userservice.security.AuthService;
import eu.mostserene.avogador.userservice.security.AuthServiceImpl.GoogleUser;
import eu.mostserene.avogador.userservice.security.ForbiddenException;
import eu.mostserene.avogador.userservice.security.InvalidDomainException;
import eu.mostserene.avogador.userservice.security.restapicontrol.DisablePublicRestAPI;
import eu.mostserene.avogador.userservice.utils.LoggerColors;
import eu.mostserene.avogador.userservice.utils.NotFoundException;
import eu.mostserene.avogador.userservice.utils.ProfileManager;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpHeaders;
import org.springframework.http.ResponseCookie;
import org.springframework.web.bind.annotation.*;

import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.TimeUnit;

@RestController
@Slf4j
@RequestMapping("/public/users")
public class UserController {

    @Autowired
    private UserService userService;

    @Autowired
    private AuthService authService;

    @Autowired
    private EmailService emailService;

    @Autowired
    private ProfileManager profileManager;

    @Value("${spring.profiles.active}")
    private String activeProfile;

    /**
     * Get the user claimed by the current JWT cookie
     * @param request the current HTTP request
     * @return the related AuthUserDTO
     */
    @GetMapping("/current")
    @DisablePublicRestAPI
    public AuthUserDTO getCurrentUser(HttpServletRequest request) {
        return authService.decodeJwt(authService.extractJwt(request));
    }

    /**
     * Get a user by id, if called by a student, and it's not themselves, the email is obfuscated
     *
     * @param user the current user from the header
     * @param userId  the id of the user
     * @return the corresponding user
     */
    @GetMapping("/{userId}")
    private AuthUserDTO getUserById(@RequestHeader(name = "User") AuthUserDTO user, @PathVariable UUID userId) {
        var responseUser = userService.getUserById(userId)
                .orElseThrow(NotFoundException::new);
        if (!user.getIsProfessor() && !user.getIsSuperuser() && !user.getId().equals(userId))
            responseUser.setEmail(null);
        return responseUser.generateAuthUserDTO();
    }

    /**
     * Get a user by their email
     *
     * @param email the email of the user
     * @return the corresponding user
     */
    @GetMapping("/email/{email}")
    private AuthUserDTO getUserByEmail(@PathVariable String email) {
        return userService.getUserByEmail(email)
                .orElseThrow(() -> new NotFoundException("User " + email)).generateAuthUserDTO();
    }

    /**
     * Delete a user by id. Only a superuser or the user itself are allowed to do that.
     *
     * @param userId the id of the user
     */
    @DeleteMapping("/{userId}")
    private void deleteUser(@RequestHeader(name = "User") AuthUserDTO user, @PathVariable UUID userId) {
        var userToDelete = userService.getUserById(userId)
                .orElseThrow(() -> new NotFoundException("User " + userId));

        user.requireSuperuser().ifPresentOrElse(
                superuser -> userService.deleteUser(userToDelete),
                () -> {
                    user.requireId(userId)
                            .orElseThrow(() -> new ForbiddenException(user));
                    userService.deleteUser(userToDelete);
                }
        );
    }

    /**
     * Login using a Google token and retrieve the associated user
     *
     * @param response    the http response
     * @param googleToken the token generated by Google
     * @return the authUserDTO containing also the profile image URL and the hash of the JWT to be used agains CSRF
     * @throws InvalidDomainException if the email domain is not in the customer's domains
     */
    @PostMapping("/google-auth")
    private AuthUserDTOImageHash authenticateWithGoogle(HttpServletResponse response, @RequestBody GoogleToken googleToken) throws InvalidDomainException {
        log.info("token: " + googleToken.getGoogleToken());
        GoogleUser googleUser = authService.getGoogleUser(googleToken.getGoogleToken());
        Optional<User> queriedUser = userService.getUserByEmail(googleUser.email());

        final User user = queriedUser.map(innerUser -> {
            if (innerUser.getGivenName().equals(googleUser.givenName()) &&
                    innerUser.getFamilyName().equals(googleUser.familyName())) {
                return innerUser;
            }
            innerUser.setGivenName(googleUser.givenName());
            innerUser.setFamilyName(googleUser.familyName());
            return userService.updateUser(innerUser);
        }).orElseGet(() -> {
            emailService.sendSimpleEmail(googleUser.email(), "Welcome to Avogador!",
                    "Hi " + googleUser.givenName() + "!\nYou have been successfully registered to Avogador, enjoy!");

            return userService.createUser(new User(
                    googleUser.email(),
                    googleUser.givenName(),
                    googleUser.familyName())
            );
        });

        ResponseCookie jwtCookie = profileManager.executeOnProfile(
                this::buildDevelopJWT,
                this::buildTestingJWT,
                this::buildStagingJWT,
                this::buildProductionJWT,
                user
        );

        log.info(LoggerColors.error(jwtCookie.toString()));

        response.addHeader(HttpHeaders.SET_COOKIE, jwtCookie.toString());

        String jwtHash = Hashing.sha256()
                .hashString(jwtCookie.getValue(), StandardCharsets.UTF_8)
                .toString();

        return new AuthUserDTOImageHash(user.generateAuthUserDTO(), googleUser.picture(),
                jwtHash.substring(jwtHash.length() - 20));
    }

    private ResponseCookie buildDevelopJWT(User user) {
        return ResponseCookie.from("develop-jwt")
                .value(authService.generateJWT(user, TimeUnit.DAYS.toMillis(8)))
                .httpOnly(true)
                .path("/")
                .domain("localhost")
                .secure(true)
                .maxAge(Duration.ofDays(7))
                .sameSite("None")
                .build();
    }

    private ResponseCookie buildTestingJWT(User user) {
        return ResponseCookie.from("testing-jwt")
                .value(authService.generateJWT(user, TimeUnit.DAYS.toMillis(8)))
                .httpOnly(true)
                .path("/")
                .secure(true)
                .maxAge(Duration.ofDays(7))
                .sameSite("None")
                .build();
    }

    private ResponseCookie buildStagingJWT(User user) {
        return ResponseCookie.from("staging-jwt")
                .value(authService.generateJWT(user, TimeUnit.DAYS.toMillis(8)))
                .httpOnly(true)
                .path("/")
                .domain("api.avogador.staging.mostserene.eu")
                .secure(true)
                .maxAge(Duration.ofDays(7))
                .sameSite("None")
                .build();
    }

    private ResponseCookie buildProductionJWT(User user) {
        return ResponseCookie.from("__Secure-jwt")
                .value(authService.generateJWT(user, TimeUnit.DAYS.toMillis(8)))
                .httpOnly(true)
                .path("/")
                // .domain("api.avogador.mostserene.eu")
                .secure(true)
                .maxAge(Duration.ofDays(7))
                .sameSite("Lax")
                .build();
    }

    /**
     * Logout from the application
     *
     * @param response the http response
     */
    @GetMapping("/logout")
    private void logoutUser(HttpServletResponse response) {
        response.addHeader(HttpHeaders.SET_COOKIE,
                profileManager.executeOnProfile(
                        this::developLogout,
                        this::testingLogout,
                        this::stagingLogout,
                        this::productionLogout
                ).toString());
    }

    private ResponseCookie developLogout() {
        return ResponseCookie.from("develop-jwt")
                .value(null)
                .httpOnly(true)
                .path("/")
                .domain("localhost")
                .secure(true)
                .maxAge(Duration.ofSeconds(1))
                .sameSite("None")
                .build();
    }

    private ResponseCookie testingLogout() {
        return ResponseCookie.from("testing-jwt")
                .value(null)
                .httpOnly(true)
                .path("/")
                .secure(true)
                .maxAge(Duration.ofSeconds(1))
                .sameSite("None")
                .build();
    }

    private ResponseCookie stagingLogout() {
        return ResponseCookie.from("staging-jwt")
                .value(null)
                .httpOnly(true)
                .path("/")
                .domain("api.avogador.staging.mostserene.eu")
                .secure(true)
                .maxAge(Duration.ofSeconds(1))
                .sameSite("None")
                .build();
    }

    private ResponseCookie productionLogout() {
        return ResponseCookie.from("__Secure-jwt")
                .value(null)
                .httpOnly(true)
                .path("/")
                // .domain("api.avogador.mostserene.eu")
                .secure(true)
                .maxAge(Duration.ofSeconds(1))
                .sameSite("Lax")
                .build();
    }


    /**
     * Revoke all the existing JWTs for the user.
     * This call is allowed only from a superuser or the user itself
     *
     * @param user    the request user
     * @param userId  the id of the user whose tokens have to be revoked
     */
    @PatchMapping("/{userId}/revoke-jwt")
    private void revokeJWTs(@RequestHeader(name = "User") AuthUserDTO user, @PathVariable UUID userId) {
        if (!user.getIsSuperuser() && !Objects.equals(user.getId(), userId)) {
            throw new ForbiddenException(user);
        }
        authService.revokeUserJWTs(userId);
    }


    private static class GoogleToken {
        private String googleToken;

        public String getGoogleToken() {
            return googleToken;
        }
    }


    private static class AuthUserDTOImageHash extends AuthUserDTO {
        private String picture;

        private String hash;


        public AuthUserDTOImageHash(UUID id, String email, String givenName, String familyName,
                                    Boolean isProfessor, Boolean isSuperuser, String picture, String hash) {
            super(id, email, givenName, familyName, isProfessor, isSuperuser);
            this.setPicture(picture);
            this.setHash(hash);
        }

        public AuthUserDTOImageHash(AuthUserDTO authUserDTO, String picture, String hash) {
            super(authUserDTO.getId(), authUserDTO.getEmail(), authUserDTO.getGivenName(), authUserDTO.getFamilyName(),
                    authUserDTO.getIsProfessor(), authUserDTO.getIsSuperuser());
            this.setPicture(picture);
            this.setHash(hash);
        }

        public String getPicture() {
            return picture;
        }

        public void setPicture(String picture) {
            this.picture = picture;
        }

        public String getHash() {
            return hash;
        }

        public void setHash(String hash) {
            this.hash = hash;
        }
    }
}
